"""
Fountain-code golden vector regression test.

Locks down the byte-exact output of the current Python LT encoder for a
fixed set of (k_blocks, block_size, seed) tuples. The Rust + WASM
fountain rewrite (Gemini #6 / docs/FOUNTAIN_RUST_WASM_MIGRATION.md)
must reproduce every vector here byte-for-byte.

Vectors live in ``tests/golden/fountain/`` and were generated by
``scripts/dev/generate_fountain_golden_vectors.py``. Re-running the
generator overwrites the vectors, which silently invalidates every
previously-encoded GIF — do NOT regenerate without an explicit reason
documented in the migration plan.

Test layout:

* ``test_golden_vectors_match`` — every vector decodes back to its
  encoder's droplet bit-for-bit.
* ``test_data_sha256_prefix_matches`` — the manifest's quick
  fingerprint matches the actual data, catching corruption in the .bin
  files (e.g. a bad git checkout).
* ``test_block_indices_match`` — independent check on the indices
  field, separate from the data check.

When the Rust binding lands (Phase 2 of the migration), this same test
file will exercise the Rust encoder by simply changing the import line.
"""

import hashlib
import json
import struct
from pathlib import Path

import pytest

from meow_decoder.fountain import FountainEncoder

GOLDEN_DIR = Path(__file__).parent / "golden" / "fountain"
MANIFEST = GOLDEN_DIR / "manifest.json"


def _make_source(total_size: int) -> bytes:
    """Mirror of ``scripts/dev/generate_fountain_golden_vectors.py``'s
    deterministic source generator. Must stay byte-identical."""
    return bytes(((i * 31 + 17) & 0xFF) for i in range(total_size))


def _droplet_to_wire(droplet) -> bytes:
    """Mirror of the generator's wire encoder — production
    `pack_droplet` format (seed u32 BE, count u16 BE, indices u16 BE,
    data raw).
    """
    head = struct.pack(">IH", droplet.seed, len(droplet.block_indices))
    indices = struct.pack(f">{len(droplet.block_indices)}H", *droplet.block_indices)
    return head + indices + droplet.data


def _load_manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def manifest():
    if not MANIFEST.exists():
        pytest.skip(
            "fountain golden vectors not present — run "
            "scripts/dev/generate_fountain_golden_vectors.py "
            "to populate tests/golden/fountain/"
        )
    return _load_manifest()


@pytest.mark.security
class TestFountainGoldenVectors:
    """Byte-exact regression net for the LT encoder.

    These vectors are the acceptance criteria for the Rust + WASM
    fountain unification (gemini #6, see migration plan in
    docs/FOUNTAIN_RUST_WASM_MIGRATION.md). When the Rust port lands,
    this test runs against the new implementation and must still pass.
    """

    def test_format_version(self, manifest):
        """Manifest format version is locked at 1 — bumping this is a
        breaking change that requires regenerating all vectors and
        validating the rewrite end-to-end."""
        assert manifest["format_version"] == 1

    def test_at_least_sixteen_vectors(self, manifest):
        """Coverage floor — k ∈ {2, 10, 100, 1000} × multiple seeds."""
        assert len(manifest["vectors"]) >= 16

    @pytest.mark.parametrize("idx", range(16))
    def test_golden_vector_byte_exact(self, manifest, idx):
        """The encoder's wire output for (k, block_size, seed) must
        match the recorded golden vector byte-for-byte."""
        v = manifest["vectors"][idx]
        source = _make_source(v["total_size"])
        encoder = FountainEncoder(source, v["k_blocks"], v["block_size"])
        droplet = encoder.droplet(seed=v["seed"])
        actual_wire = _droplet_to_wire(droplet)

        expected_wire = (GOLDEN_DIR / v["file"]).read_bytes()
        assert actual_wire == expected_wire, (
            f"Encoder output drift: vector {v['file']} "
            f"(k={v['k_blocks']}, block_size={v['block_size']}, seed={v['seed']}). "
            f"Expected {len(expected_wire)} bytes, got {len(actual_wire)}. "
            "If this is intentional (algorithm change), regenerate vectors via "
            "scripts/dev/generate_fountain_golden_vectors.py and document the "
            "compatibility break."
        )

    @pytest.mark.parametrize("idx", range(16))
    def test_block_indices_match_manifest(self, manifest, idx):
        """Independent check on the block_indices field — catches a class
        of bugs where the data XOR happens to match but the indices field
        diverges (or vice versa)."""
        v = manifest["vectors"][idx]
        source = _make_source(v["total_size"])
        encoder = FountainEncoder(source, v["k_blocks"], v["block_size"])
        droplet = encoder.droplet(seed=v["seed"])
        assert list(droplet.block_indices) == v["block_indices"]

    @pytest.mark.parametrize("idx", range(16))
    def test_data_sha256_prefix_matches_manifest(self, manifest, idx):
        """Cross-check the binary file with the manifest fingerprint —
        catches `tests/golden/fountain/*.bin` corruption (bad git
        checkout, partial copy)."""
        v = manifest["vectors"][idx]
        wire = (GOLDEN_DIR / v["file"]).read_bytes()
        # Skip the 4-byte seed + 2-byte block_count + 2*block_count indices header
        head_len = 4 + 2 + 2 * len(v["block_indices"])
        data_part = wire[head_len:]
        actual_prefix = hashlib.sha256(data_part).hexdigest()[:16]
        assert actual_prefix == v["data_sha256_prefix"], (
            f"Vector {v['file']} data section appears corrupted: "
            f"expected sha256 prefix {v['data_sha256_prefix']}, got "
            f"{actual_prefix}."
        )
