/**
 * qrDecoder.test.ts — Unit tests for all QR payload format parsers.
 *
 * Covers every format the web demo and CLI can produce.
 */

import {
  parseFountainPayload,
  parseSingleFramePayload,
  parseLegacyChunkedPayload,
  parseJsonPayload,
  parseQRPayload,
  isMeowQRPayload,
  QR_PREFIXES,
} from '../src/services/qrDecoder';

// ── Shared helpers ────────────────────────────────────────────────────────────

const validB64 = 'AABgACAAIABgACAAIABgACAAIABgAA=='; // arbitrary valid base64

// ── FOUNTAIN: ─────────────────────────────────────────────────────────────────

describe('parseFountainPayload', () => {
  it('parses a valid FOUNTAIN: string', () => {
    const qr = `FOUNTAIN:10:600:4523:${validB64}`;
    const result = parseFountainPayload(qr);
    expect(result).not.toBeNull();
    expect(typeof result?.index).toBe('number');
    expect(result?.data).toBe(qr); // full string stored
  });

  it('returns null for non-FOUNTAIN string', () => {
    expect(parseFountainPayload('MEOW:' + validB64)).toBeNull();
  });

  it('returns null for malformed FOUNTAIN (too few parts)', () => {
    expect(parseFountainPayload('FOUNTAIN:10:600')).toBeNull();
  });

  it('returns null for FOUNTAIN with invalid kBlocks', () => {
    expect(parseFountainPayload(`FOUNTAIN:abc:600:4523:${validB64}`)).toBeNull();
    expect(parseFountainPayload(`FOUNTAIN:0:600:4523:${validB64}`)).toBeNull();
  });

  it('deduplicates identical FOUNTAIN frames (same hash)', () => {
    const qr = `FOUNTAIN:10:600:4523:${validB64}`;
    const a = parseFountainPayload(qr);
    const b = parseFountainPayload(qr);
    expect(a?.index).toBe(b?.index);
  });

  it('produces different indices for different droplets', () => {
    const a = parseFountainPayload(`FOUNTAIN:10:600:4523:${validB64}`);
    const b = parseFountainPayload(`FOUNTAIN:10:600:4523:BBBgACAAIABgACAAIABgACAAIABgAA==`);
    expect(a?.index).not.toBe(b?.index);
  });
});

// ── Single-frame prefixes ─────────────────────────────────────────────────────

describe('parseSingleFramePayload', () => {
  it.each([
    ['MEOW:', `MEOW:${validB64}`],
    ['FS:', `FS:${validB64}`],
    ['QUANTUM:', `QUANTUM:${validB64}`],
    ['HYBRID-PQ:', `HYBRID-PQ:${validB64}`],
    ['DURESS:', `DURESS:${validB64}`],
  ])('parses %s format', (_prefix, qr) => {
    const result = parseSingleFramePayload(qr);
    expect(result).not.toBeNull();
    expect(result?.data).toBe(qr); // full string stored with prefix
    expect(typeof result?.index).toBe('number');
  });

  it('returns null for FOUNTAIN: (not single-frame)', () => {
    expect(parseSingleFramePayload(`FOUNTAIN:10:600:4523:${validB64}`)).toBeNull();
  });

  it('returns null for empty string', () => {
    expect(parseSingleFramePayload('')).toBeNull();
  });

  it('returns null for too-short string', () => {
    expect(parseSingleFramePayload('MEOW:A')).toBeNull();
  });

  it('deduplicates same QR value (same index)', () => {
    const qr = `MEOW:${validB64}`;
    expect(parseSingleFramePayload(qr)?.index).toBe(parseSingleFramePayload(qr)?.index);
  });

  it('FS: and MEOW: produce different indices for different payloads', () => {
    const a = parseSingleFramePayload(`MEOW:${validB64}`);
    const b = parseSingleFramePayload(`FS:${validB64}`);
    expect(a?.index).not.toBe(b?.index);
  });
});

// ── Legacy MEOW-N/total: ──────────────────────────────────────────────────────

describe('parseLegacyChunkedPayload', () => {
  it('parses first chunk (1-based → 0-based)', () => {
    const qr = `MEOW-1/5:${validB64}`;
    const result = parseLegacyChunkedPayload(qr);
    expect(result).not.toBeNull();
    expect(result?.index).toBe(0); // 1-based → 0-based
    expect(result?.data).toBe(qr);
  });

  it('parses middle chunk', () => {
    expect(parseLegacyChunkedPayload(`MEOW-3/5:${validB64}`)?.index).toBe(2);
  });

  it('parses last chunk', () => {
    expect(parseLegacyChunkedPayload(`MEOW-5/5:${validB64}`)?.index).toBe(4);
  });

  it('returns null for non-chunked MEOW: string', () => {
    expect(parseLegacyChunkedPayload(`MEOW:${validB64}`)).toBeNull();
  });

  it('returns null for malformed chunk string', () => {
    expect(parseLegacyChunkedPayload('MEOW-abc/5:' + validB64)).toBeNull();
    expect(parseLegacyChunkedPayload('MEOW-0/5:' + validB64)).toBeNull(); // N must be >= 1
    expect(parseLegacyChunkedPayload('MEOW-1/')).toBeNull(); // no colon
  });

  // DURESS-N/total: — generated by web demo for large DURESS payloads (> 2500 chars)
  it('parses DURESS-1/3: (first chunk, index 0)', () => {
    const qr = `DURESS-1/3:${validB64}`;
    const result = parseLegacyChunkedPayload(qr);
    expect(result).not.toBeNull();
    expect(result?.index).toBe(0);
    expect(result?.data).toBe(qr);
  });

  it('parses DURESS-2/3: (middle chunk, index 1)', () => {
    expect(parseLegacyChunkedPayload(`DURESS-2/3:${validB64}`)?.index).toBe(1);
  });

  it('parses DURESS-3/3: (last chunk, index 2)', () => {
    expect(parseLegacyChunkedPayload(`DURESS-3/3:${validB64}`)?.index).toBe(2);
  });

  it('returns null for DURESS-0/3: (chunk N must be >= 1)', () => {
    expect(parseLegacyChunkedPayload(`DURESS-0/3:${validB64}`)).toBeNull();
  });
});

// ── JSON envelope ─────────────────────────────────────────────────────────────

describe('parseJsonPayload', () => {
  it('parses valid JSON envelope', () => {
    const qr = JSON.stringify({ index: 7, data: validB64 });
    const result = parseJsonPayload(qr);
    expect(result?.index).toBe(7);
    expect(result?.data).toBe(validB64);
  });

  it('accepts matching session_id', () => {
    const qr = JSON.stringify({ index: 0, data: validB64, session_id: 'abc' });
    expect(parseJsonPayload(qr, 'abc')).not.toBeNull();
  });

  it('rejects mismatched session_id', () => {
    const qr = JSON.stringify({ index: 0, data: validB64, session_id: 'abc' });
    expect(parseJsonPayload(qr, 'xyz')).toBeNull();
  });

  it('accepts missing session_id regardless of expected', () => {
    const qr = JSON.stringify({ index: 0, data: validB64 });
    expect(parseJsonPayload(qr, 'expected-session')).not.toBeNull();
  });

  it('returns null for invalid JSON', () => {
    expect(parseJsonPayload('{not json')).toBeNull();
  });

  it('returns null for JSON missing index', () => {
    expect(parseJsonPayload(JSON.stringify({ data: validB64 }))).toBeNull();
  });

  it('returns null for JSON missing data', () => {
    expect(parseJsonPayload(JSON.stringify({ index: 0 }))).toBeNull();
  });

  it('returns null for non-base64 data field', () => {
    expect(parseJsonPayload(JSON.stringify({ index: 0, data: '!!!invalid!!!' }))).toBeNull();
  });
});

// ── parseQRPayload dispatcher ─────────────────────────────────────────────────

describe('parseQRPayload', () => {
  it('routes FOUNTAIN: correctly', () => {
    const qr = `FOUNTAIN:10:600:1234:${validB64}`;
    expect(parseQRPayload(qr)).not.toBeNull();
  });

  it.each([
    `MEOW:${validB64}`,
    `FS:${validB64}`,
    `QUANTUM:${validB64}`,
    `HYBRID-PQ:${validB64}`,
    `DURESS:${validB64}`,
  ])('routes single-frame %s correctly', qr => {
    expect(parseQRPayload(qr)).not.toBeNull();
  });

  it('routes legacy chunked MEOW-N/total: correctly', () => {
    expect(parseQRPayload(`MEOW-2/5:${validB64}`)).not.toBeNull();
  });

  it('routes JSON envelope correctly', () => {
    expect(parseQRPayload(JSON.stringify({ index: 0, data: validB64 }))).not.toBeNull();
  });

  it('returns null for empty string', () => {
    expect(parseQRPayload('')).toBeNull();
  });

  it('returns null for random noise', () => {
    expect(parseQRPayload('hello world')).toBeNull();
    expect(parseQRPayload('https://example.com')).toBeNull();
  });

  it('stores the session_id from JSON envelope', () => {
    const qr = JSON.stringify({ index: 2, data: validB64, session_id: 'sess-123' });
    expect(parseQRPayload(qr)?.session_id).toBe('sess-123');
  });
});

// ── isMeowQRPayload ───────────────────────────────────────────────────────────

describe('isMeowQRPayload', () => {
  it.each([
    `FOUNTAIN:10:600:1234:${validB64}`,
    `MEOW:${validB64}`,
    `FS:${validB64}`,
    `QUANTUM:${validB64}`,
    `HYBRID-PQ:${validB64}`,
    `DURESS:${validB64}`,
    `MEOW-1/3:${validB64}`,
    `DURESS-1/3:${validB64}`,   // large DURESS: split into chunked frames
    `DURESS-2/3:${validB64}`,
    JSON.stringify({ index: 0, data: validB64 }),
  ])('returns true for valid meow format: %s', qr => {
    expect(isMeowQRPayload(qr)).toBe(true);
  });

  it.each([
    '',
    'hello',
    'https://example.com',
    '{"not":"meow"}',
  ])('returns false for non-meow: %s', qr => {
    expect(isMeowQRPayload(qr)).toBe(false);
  });
});

// ── QR_PREFIXES constant ──────────────────────────────────────────────────────

describe('QR_PREFIXES', () => {
  it('exports all expected prefix constants', () => {
    expect(QR_PREFIXES.FOUNTAIN).toBe('FOUNTAIN:');
    expect(QR_PREFIXES.MEOW).toBe('MEOW:');
    expect(QR_PREFIXES.FORWARD_SECRECY).toBe('FS:');
    expect(QR_PREFIXES.QUANTUM).toBe('QUANTUM:');
    expect(QR_PREFIXES.HYBRID_PQ).toBe('HYBRID-PQ:');
    expect(QR_PREFIXES.DURESS).toBe('DURESS:');
    expect(QR_PREFIXES.MEOW_CHUNKED).toBe('MEOW-');
    expect(QR_PREFIXES.DURESS_CHUNKED).toBe('DURESS-'); // large-duress split format
  });
});
