/**
 * HomeScreen.tsx — Main landing screen.
 *
 * Two entry paths:
 *   1. Load a capture request JSON file (from Downloads via file picker)
 *   2. Manual entry — user types session ID and expected frame count
 *
 * Validates the loaded JSON with Zod before allowing navigation to
 * CaptureScreen, showing clear field-level errors on failure.
 */

import React, { useState, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  TextInput,
  ScrollView,
  Alert,
  SafeAreaView,
  Platform,
  ActivityIndicator,
} from 'react-native';
import DocumentPicker from 'react-native-document-picker';
import RNFS from 'react-native-fs';
import { z } from 'zod';
import {
  validateRequestFromString,
  firstErrorMessage,
} from '../services/requestValidator';
import type { CaptureRequest } from '../types/capture';
import type { HomeScreenProps } from '../types/navigation';
import { Colors, Typography, Spacing, Radius, Shadows } from '../constants/theme';
import { DEFAULT_TIMEOUT_SECONDS } from '../constants/config';

// ── Component ─────────────────────────────────────────────────────────────────

export function HomeScreen({ navigation }: HomeScreenProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Manual entry state
  const [manualMode, setManualMode] = useState(false);
  const [sessionId, setSessionId] = useState('');
  const [expectedFrames, setExpectedFrames] = useState('');
  const [timeoutSecs, setTimeoutSecs] = useState(String(DEFAULT_TIMEOUT_SECONDS));

  const navigateToCapture = useCallback(
    (request: CaptureRequest) => {
      navigation.navigate('Capture', { request });
    },
    [navigation],
  );

  // ── Load from JSON file ────────────────────────────────────────────────────

  const loadFromFile = useCallback(async () => {
    setError(null);
    setLoading(true);
    try {
      const [result] = await DocumentPicker.pick({
        type: [DocumentPicker.types.json],
        allowMultiSelection: false,
      });

      const content = await RNFS.readFile(
        Platform.OS === 'android' ? result.uri : decodeURIComponent(result.uri),
        'utf8',
      );

      const request = validateRequestFromString(content);
      navigateToCapture(request);
    } catch (err) {
      if (DocumentPicker.isCancel(err)) {
        // User cancelled — not an error
        return;
      }
      if (err instanceof z.ZodError) {
        setError(`Invalid request: ${firstErrorMessage(err)}`);
      } else if (err instanceof SyntaxError) {
        setError('File is not valid JSON');
      } else {
        setError('Could not read file');
      }
    } finally {
      setLoading(false);
    }
  }, [navigateToCapture]);

  // ── Manual entry ───────────────────────────────────────────────────────────

  const startManual = useCallback(() => {
    setError(null);
    const rawRequest = {
      action: 'capture',
      session_id: sessionId.trim(),
      expected_frames: parseInt(expectedFrames.trim(), 10),
      timeout_seconds: parseInt(timeoutSecs.trim(), 10) || DEFAULT_TIMEOUT_SECONDS,
    };

    try {
      const request = validateRequestFromString(JSON.stringify(rawRequest));
      navigateToCapture(request);
    } catch (err) {
      if (err instanceof z.ZodError) {
        setError(firstErrorMessage(err));
      } else {
        setError('Invalid input');
      }
    }
  }, [sessionId, expectedFrames, timeoutSecs, navigateToCapture]);

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <SafeAreaView style={styles.safe}>
      <ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">
        {/* Header */}
        <Text style={styles.title}>🐱 meow-decoder</Text>
        <Text style={styles.subtitle}>Optical QR Capture</Text>

        {/* Error banner */}
        {error && (
          <View style={styles.errorBanner}>
            <Text style={styles.errorText}>🙀 {error}</Text>
          </View>
        )}

        {/* Load from file */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Load Capture Request</Text>
          <Text style={styles.cardBody}>
            Select the JSON file generated by{' '}
            <Text style={styles.code}>meow-decoder encode</Text>
          </Text>
          <TouchableOpacity
            style={styles.primaryButton}
            onPress={loadFromFile}
            disabled={loading}
            accessibilityRole="button"
          >
            {loading ? (
              <ActivityIndicator color={Colors.textPrimary} />
            ) : (
              <Text style={styles.primaryButtonText}>📂 Load JSON File</Text>
            )}
          </TouchableOpacity>
        </View>

        {/* Divider */}
        <View style={styles.divider}>
          <View style={styles.dividerLine} />
          <Text style={styles.dividerText}>or enter manually</Text>
          <View style={styles.dividerLine} />
        </View>

        {/* Manual entry */}
        <TouchableOpacity
          style={styles.manualToggle}
          onPress={() => setManualMode((v) => !v)}
        >
          <Text style={styles.manualToggleText}>
            {manualMode ? '▲ Hide manual entry' : '▼ Enter session details'}
          </Text>
        </TouchableOpacity>

        {manualMode && (
          <View style={styles.card}>
            <LabelledInput
              label="Session ID (UUID)"
              value={sessionId}
              onChangeText={setSessionId}
              placeholder="550e8400-e29b-41d4-a716-446655440000"
              autoCapitalize="none"
              autoCorrect={false}
            />
            <LabelledInput
              label="Expected Frames"
              value={expectedFrames}
              onChangeText={setExpectedFrames}
              placeholder="45"
              keyboardType="number-pad"
            />
            <LabelledInput
              label={`Timeout (seconds, default ${DEFAULT_TIMEOUT_SECONDS})`}
              value={timeoutSecs}
              onChangeText={setTimeoutSecs}
              placeholder={String(DEFAULT_TIMEOUT_SECONDS)}
              keyboardType="number-pad"
            />
            <TouchableOpacity
              style={styles.primaryButton}
              onPress={startManual}
              accessibilityRole="button"
            >
              <Text style={styles.primaryButtonText}>🐾 Start Capture</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Info footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Frames are exported as JSON to Downloads for USB retrieval.
            No data is transmitted over the network.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

// ── Sub-component ─────────────────────────────────────────────────────────────

function LabelledInput({
  label,
  ...props
}: { label: string } & React.ComponentProps<typeof TextInput>) {
  return (
    <View style={inputStyles.container}>
      <Text style={inputStyles.label}>{label}</Text>
      <TextInput
        style={inputStyles.input}
        placeholderTextColor={Colors.textDisabled}
        {...props}
      />
    </View>
  );
}

const inputStyles = StyleSheet.create({
  container: { marginBottom: Spacing.md },
  label: {
    color: Colors.textSecondary,
    fontSize: Typography.sm,
    marginBottom: Spacing.xxs,
  },
  input: {
    color: Colors.textPrimary,
    fontSize: Typography.md,
    backgroundColor: Colors.backgroundTertiary,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.surfaceBorder,
  },
});

// ── Styles ─────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.background },
  scroll: { padding: Spacing.lg, paddingBottom: Spacing.xxxl },
  title: {
    color: Colors.catOrange,
    fontSize: Typography.xxl,
    fontWeight: Typography.heavy,
    textAlign: 'center',
    marginTop: Spacing.xl,
  },
  subtitle: {
    color: Colors.textSecondary,
    fontSize: Typography.md,
    textAlign: 'center',
    marginBottom: Spacing.xl,
  },
  errorBanner: {
    backgroundColor: 'rgba(255,59,48,0.15)',
    borderRadius: Radius.md,
    borderLeftWidth: 3,
    borderLeftColor: Colors.danger,
    padding: Spacing.md,
    marginBottom: Spacing.md,
  },
  errorText: {
    color: Colors.danger,
    fontSize: Typography.sm,
  },
  card: {
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    marginBottom: Spacing.lg,
    ...Shadows.subtle,
  },
  cardTitle: {
    color: Colors.textPrimary,
    fontSize: Typography.lg,
    fontWeight: Typography.semibold,
    marginBottom: Spacing.xs,
  },
  cardBody: {
    color: Colors.textSecondary,
    fontSize: Typography.sm,
    marginBottom: Spacing.lg,
    lineHeight: Typography.sm * 1.5,
  },
  code: {
    color: Colors.catOrangeLight,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  primaryButton: {
    backgroundColor: Colors.catOrange,
    paddingVertical: Spacing.md,
    borderRadius: Radius.full,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: Colors.textPrimary,
    fontSize: Typography.md,
    fontWeight: Typography.bold,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: Spacing.lg,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.surfaceBorder,
  },
  dividerText: {
    color: Colors.textTertiary,
    fontSize: Typography.sm,
    marginHorizontal: Spacing.sm,
  },
  manualToggle: { alignItems: 'center', marginBottom: Spacing.md },
  manualToggleText: {
    color: Colors.catOrange,
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
  },
  footer: {
    marginTop: Spacing.xl,
    alignItems: 'center',
  },
  footerText: {
    color: Colors.textTertiary,
    fontSize: Typography.xs,
    textAlign: 'center',
    lineHeight: Typography.xs * 1.6,
  },
});
