/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmresult_free: (a: number, b: number) => void;
export const __wbg_wasmx25519keypair_free: (a: number, b: number) => void;
export const constant_time_compare: (a: number, b: number, c: number, d: number) => number;
export const decode_data: (a: number, b: number, c: number, d: number) => number;
export const decrypt: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const decrypt_with_forward_secrecy: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const derive_key: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const encode_data: (a: number, b: number, c: number, d: number, e: number) => number;
export const encrypt: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => number;
export const encrypt_with_forward_secrecy: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const generate_nonce: () => number;
export const generate_salt: () => number;
export const hash_sha256: (a: number, b: number) => any;
export const hkdf: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const hmac: (a: number, b: number, c: number, d: number) => any;
export const init: () => void;
export const pq_available: () => number;
export const random: (a: number) => number;
export const secure_clear: (a: number, b: number, c: any) => void;
export const verify_hmac: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const version: () => [number, number];
export const wasmresult_data: (a: number) => any;
export const wasmresult_error: (a: number) => [number, number];
export const wasmresult_success: (a: number) => number;
export const wasmx25519keypair_new: () => [number, number, number];
export const wasmx25519keypair_public_key: (a: number) => any;
export const x25519_diffie_hellman: (a: number, b: number, c: number, d: number) => number;
export const x25519_generate_keypair: () => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
